# Generated by Django 5.1.1 on 2024-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_name_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('BUY', 'Buyer'), ('SUP', 'Supplier')], max_length=5),
        ),
    ]
