# Generated by Django 5.1.1 on 2024-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_shipaddr_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipaddr',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipaddr',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipaddr',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipaddr',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipaddr',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipaddr',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipaddr',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipaddr',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
