# Generated by Django 5.1.1 on 2024-10-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='full_name',
        ),
    ]
