# Generated by Django 5.1.1 on 2024-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_shoppinglist_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], default='pending', max_length=10),
        ),
    ]
