# Generated by Django 5.1.1 on 2024-11-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipAddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NOT INCLUDED', max_length=255)),
                ('email', models.EmailField(default='NOT INCLUDED', max_length=255)),
                ('address', models.CharField(default='NOT INCLUDED', max_length=255)),
                ('city', models.CharField(default='NOT INCLUDED', max_length=255)),
                ('country', models.CharField(default='NOT INCLUDED', max_length=255)),
                ('postal_code', models.CharField(default='NOT INCLUDED', max_length=10)),
                ('phone_number', models.CharField(default='NOT INCLUDED', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_address', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ship_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_addr', to='orders.shipaddr'),
        ),
    ]
