# Generated by Django 5.1.1 on 2024-11-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shipaddr_order_ship_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipaddr',
            name='full_name',
            field=models.CharField(default='NOT INCLUDED', max_length=255),
        ),
    ]
