# Generated by Django 5.1.1 on 2024-12-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_product'),
        ('products', '0008_orderproductsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orderproductsnapshot'),
        ),
    ]
