# Generated by Django 5.1.1 on 2024-12-08 20:59

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_orderproductsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductsnapshot',
            name='pieces_per_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces_per_unit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
